### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by grofit** [warrenseine/prettier-plugin-csharp#2]
Any chance you can add a bare bones "example usage" to the docs, i.e how to include it in node, format some code etc?

I assume it would be just calling prettier with this listed as a plugin, but that would be helpful to new users.

**Comment by warrenseine** [comment]
Yes, I will, in a similar way as https://github.com/prettier/plugin-python/blob/master/README.md

Currently, it wouldn't make sense to use the plugin for anything else than developing it, because it *will* break your code. I'm about to push a proper "alpha" in the coming days.

I'll leave this issue open until then.

**Comment by grofit** [comment]
No rush buddy, thanks for sorting it for us.

**Comment by warrenseine** [comment]
Done.
