### ISSUE TITLE
Bug: Embedded Empty Statements are deleted

### ISSUE THREAD

**Issue by CharlesTaylor7** [warrenseine/prettier-plugin-csharp#24]
This
```csharp
    if (true);
    while (false) ;
    foreach (var x in "") ;
```
gets transformed to this
```csharp
    if (true)
        while (false) 
            foreach (var x in "") 
```

I started on a fix for this, but I had a few questions. 

1. Why does `if` use an `if_body` node, but `while` & `foreach`, etc., use an `embedded_statement` node?

2. Is it better to update the grammar to have a special node for required embedded empty statements, or encode the logic solely at the printer level?

**Comment by warrenseine** [comment]
Wow, good catch!

1. I don't know. They are exactly the same. I can see that it is the case in the original [grammar](https://github.com/antlr/grammars-v4/blob/master/csharp/CSharpParser.g4#L361). I wouldn't mind if you removed `if_body`.

2. I don't really understand what's happening here. The empty statement should be matched by the `simple_embedded_statement : ';'` rule. Why would the `while_statement` get eaten by the `if_body`? I'd dump the JSON AST [returned by ANTLR](https://github.com/warrenseine/prettier-plugin-csharp/blob/master/src/parser.js#L35) and confirm it first. I'm not sure a new node would help here, since there's already this `simple_embedded_statement : ';'` rule. And the printer shouldn't care whether the previous statement was empty, so I don't think we should need custom logic here.

The only special case I can think of for empty conditional statement is the indentation:

`if (true);` should be printed as
```
if (true)
    ;
```

while `if (true) { ... }` should be printed as
```
if (true)
{
    ...
}
```

The block is not indented, only it's content. There's some logic in `printIfStatement` for instance. But it's doesn't seem to be the cause here.

Anyway, I'm curious so I'll look at it a little bit on my own, but I'd love to see your fix.

**Comment by CharlesTaylor7** [comment]
Resolved by https://github.com/warrenseine/prettier-plugin-csharp/commit/1a92b15765179e7df4558d522cd9b4899e05d46a
