### ISSUE TITLE
question: support for different csharp versions

### ISSUE THREAD

**Issue by jannikbuschke** [warrenseine/prettier-plugin-csharp#40]
hi @warrenseine,
Thank you for your work, looks promising.

I have several related questions that Ill just bundle here:

 - What would it take to support newer versions of C# and even other flavors, i.e. CSharp Scripting?
 - Would the antlr project be the right place to implement the grammar?
 - Do you know if other projects can be reused, i.e. Visual Studio already has code formatting and MS has made a lot of stuff open source? Maybe they also have some sort of "grammar" files somewhere?
 - General question about grammar vs formatting: I assume the grammar is some kind of ruleset or syntax about what is considered "the language", whereas formatting is only concerned about all whitespaces and linebreaks. It seems that the formatting is defined in `src/printer.js`. Am I roughly correct?

**Comment by warrenseine** [comment]
>What would it take to support newer versions of C# and even other flavors, i.e. CSharp Scripting?

I try to keep up with C# upgrades but it doesn't current support all of C# 7, so they're still a bunch of things to implement. I don't have the list at the moment.

C# scripting is probably a trivial alternative to C# so I'm pretty sure it could fit in the existing C# grammar of the plugin.

>Would the antlr project be the right place to implement the grammar?

No, ANTLR is a parser generator. It doesn't officially provide grammars. The only I'm implementing at the moment is an upgrade of https://github.com/antlr/grammars-v4/tree/master/csharp.

>Do you know if other projects can be reused, i.e. Visual Studio already has code formatting and MS has made a lot of stuff open source? Maybe they also have some sort of "grammar" files somewhere?

No they don't. Trust me, I've looked :) C# doesn't have an up-to-date grammar specification.

One alternative is to use the actual Roslyn compiler instead of a custom grammar, and you can find the beginning of an implementation on a branch: https://github.com/warrenseine/prettier-plugin-csharp/tree/roslyn.

>General question about grammar vs formatting: I assume the grammar is some kind of ruleset or syntax about what is considered "the language", whereas formatting is only concerned about all whitespaces and linebreaks. It seems that the formatting is defined in src/printer.js. Am I roughly correct?

Yes, you are. Parsing and printer are different and implemented in different files, but they are also tightly coupled. As we don't have an official AST specification, the printer expects a specific AST from the parser, so you can't just drop-in any parser and hope get it formatted. In other words, a lot of language logic exists in the printer.

**Comment by jannikbuschke** [comment]
Thanks for the explanations.

Follow up question regarding C# scripting:

If I understand you correctly allowing to have c# code (and functions) on the root level of a file (i.e. not nested in any namespace, class or function) is totally doable and could be directly supported by this plugin?

C# scripting also has some way of referencing other dlls, to give an example I think the following is something I would want to be supported:

```csharp

// Reference to an assembly
#r "Newtonsoft.Json.dll"

using System;
using Newtonsoft.Json;

// class without namespace
class Product
{
	public Guid Id{get;set;}
	public string Name{get;set;}
	public bool Enabled{get;set;}
}

// function without namespace and class
void Foo() {

}

// some code without namespace, class and function
var productObj = new Product {
	Id = Guid.NewGuid(),
	Name = "FooBar",
	Enabled = true
};

Console.WriteLine(JsonConvert.SerializeObject(productObj));
```

**Comment by warrenseine** [comment]
Yes, I believe it should be easy to implement in the current parser and printer.

Not sure how I’d do it, but two ways I can think of:
- Add a new `compilation_unit` that allows all these new rules at the root of the file.
- Fit new rules into the existing `compilation_unit` (could be tricky as the printer already makes some assumptions that could break usual C# code).

Not much to do on the printer side I think.
