### ISSUE TITLE
Inconsistent #if ... #endif blocks reformatting

### ISSUE THREAD

**Issue by GwynethLlewelyn** [warrenseine/prettier-plugin-csharp#46]
Hi! Thanks for this plugin; I'm very well aware that it's still considered in 'alpha' stage, but it already does some amazing things, which is really great!

I'm no professional C# programmer, and that's why prettifying other people's code to make it more consistently readable is so useful for me. Yesterday I came across some conditional compilation rules such as:

```csharp
		public static void WriteInfo(
			string message
#if VERBOSE_MESSAGES
			, [CallerMemberName] string callingMethod = "",
			[CallerFilePath] string callingFilePath = "",
			[CallerLineNumber] int callingFileLineNumber = 0
#endif
		)
		{
#if VERBOSE_MESSAGES
			message =
				message +
				"; from " +
				callingMethod +
				"(" +
				Path.GetFileName(callingFilePath) +
				":" +
				callingFileLineNumber +
				")";
#endif
			restbotLog.Info(message);
			Output("[INFO] " + message, ConsoleColor.White);
		}
```

which gets turned by this plugin into:

```csharp
		public static void WriteInfo(
			string message,
#if VERBOSE_MESSAGES
			[CallerMemberName] string callingMethod = "",
			[CallerFilePath] string callingFilePath = "",
			[CallerLineNumber] int callingFileLineNumber = 0
		)
		{
#if VERBOSE_MESSAGES
			message =
				message +
				"; from " +
				callingMethod +
				"(" +
				Path.GetFileName(callingFilePath) +
				":" +
				callingFileLineNumber +
				")";
#endif
			restbotLog.Info(message);
			Output("[INFO] " + message, ConsoleColor.White);
		}

#endif
```

It's actually interesting to see _why_ this happens; there is clearly some cleverness under the skin to get the parser to produce this output!

**Comment by warrenseine** [comment]
Conditional macros are an interesting beast, because they can produce valid or invalid code based on values that are not available at formatting-time. It's pretty pointless to try to evaluate them before formatting the code. IIRC, macros are naively treated as if they were comments. The same reformatting rules apply, including the difference between `/* */` vs `//` comments. And just like when you nest comments (`/* /* foo */ */`), the parser often breaks.

I'm not sure why the formatter swaps the directives here, but yes, there is some logic that treats `#if` and `#endif` differently. You can see bits of it [here](https://github.com/warrenseine/prettier-plugin-csharp/blob/535339e0a4a3ec4a5a2d7e1ecf1abf073ce19aa9/src/printer.js#L4033).

While it may be interesting to explore and learn, this plugin is basically abandoned so do not rely on it for serious usage. I'm not even writing C# anymore, so unlikely to tackle this challenge again. It was fun though!

**Comment by GwynethLlewelyn** [comment]
Thanks for your answer, and I'm sorry for only replying today... aye, your explanation makes sense; it just shows how impossibly complex C# is, to the point that _automatically parsing_ it becomes a nightmare...

I've since then found one oddity or another, but I most certainly won't bother you if you're not actively developing this plugin. In fact, I hate C# with a vengeance; whoever came up with it ought to be hanged, quartered, and their remaining body parts fed to the beasts. I _do_ respect Microsoft's absolutely fantastic work done with their super-fast compilers, though; I also admire the poor technical writers that are writing piles and piles of documentation for a language which seems to grow like a cancer, expanding in all directions... a decade ago, I had to struggle with it to continue development of an academic project (because there were already a few tens of thousands of lines of code written...), and I professed the solemn oath of never coming back to C# again. Alas, such is the irony of fate: ten years later, here I am, facing the _same_ project (which underwent several layers of mutations by others) I had buried long ago, and, like a good zombie, rises from its grave (the old Google Code archive...), bites me in the back, and drags me back into the insomniac realms of C# programming...

Anyway... sorry for the long ramble! And I'm closing this issue; you might wish to tag it as 'won't fix' or anything similar.
