### ISSUE TITLE
What is the current status on this plugin?

### ISSUE THREAD

**Issue by kristianmandrup** [warrenseine/prettier-plugin-csharp#9]
I assume it only works with VS code? Is the Readme up to date, ie. will it still `break the code`?
Do you have a changelog so we can follow the feature/stability progress?
Also, does it work on individual open files or can I import an existing project and have all the `.cs` files prettified in one go?

Thanks for any response that clarifies these questions.

Cheers ;)

**Comment by kristianmandrup** [comment]
Ah, I see. Not yet released as a proper VS Code extension but only works as CLI tool

`yarn add --dev --exact prettier prettier-csharp`

To prettify all `.cs` project files recursively...

`prettier --plugin=prettier-csharp --parser=cs --write "**/*.cs"`

Any plans to make it into a VS Code extension? Perhaps look at existing prettier extensions out there.

**Comment by warrenseine** [comment]
Hello, sorry for answering late. As you guessed, this project only focuses on the Prettier plugin. Any integration issue is likely to be handled by the editor plugin itself.

However, as reported in #11, I was using a name for the project that did not fit Prettier conventions / expectations. Now that it is fixed, the VS Code extension should be able to use it. I’ll try.

I personally use VS Code for the development of the plugin so I’ll make sure it works in the future.

Regarding the status of the plugin, I’d say that it has improved a lot in the recent months and I ran it on hundreds of files. But since it only supports C# 6 (and some C# 7 syntax additions, but not all yet), it’s likely unusable for most codebases. If you use it, please commit before formatting, then review diffs carefully after formatting.
